-- SCHOLARTRACK: Complete database and security setup
-- Run this entire file once in Supabase SQL Editor.

create table if not exists scholarship_programs (
  id bigint generated by default as identity primary key,
  name text not null unique,
  minimum_gpa numeric(3,2) not null check (minimum_gpa between 1.00 and 5.00),
  is_active boolean not null default true
);

create table if not exists scholars (
  student_no text primary key,
  full_name text not null,
  course text not null,
  program_id bigint not null references scholarship_programs(id),
  status text not null default 'Active' check (status in (
    'Active', 'Pending Submission', 'For Verification', 'Compliant',
    'With Deficiency', 'Probationary', 'For Renewal', 'Renewed', 'Disqualified'
  )),
  created_at timestamptz not null default now()
);

create table if not exists grade_submissions (
  id bigint generated by default as identity primary key,
  student_no text not null references scholars(student_no) on delete cascade,
  academic_year text not null,
  semester text not null,
  gwa numeric(3,2) not null check (gwa between 1.00 and 5.00),
  document_name text,
  submission_status text not null default 'For Verification' check (
    submission_status in ('For Verification', 'Verified', 'Returned')
  ),
  submitted_at timestamptz not null default now(),
  verified_at timestamptz,
  unique(student_no, academic_year, semester)
);

insert into scholarship_programs (name, minimum_gpa) values
  ('University Merit Scholarship', 1.75),
  ('Government Educational Grant', 2.00),
  ('Private Foundation Scholarship', 2.25),
  ('Academic Excellence Grant', 1.50)
on conflict (name) do nothing;

-- Classroom prototype access: the website handles the staff login screen.
-- Do not use real student data while public access is enabled.
alter table scholarship_programs disable row level security;
alter table scholars disable row level security;
alter table grade_submissions disable row level security;

drop policy if exists "signed in users manage programs" on scholarship_programs;
drop policy if exists "signed in users manage scholars" on scholars;
drop policy if exists "signed in users manage submissions" on grade_submissions;

create policy "signed in users manage programs"
on scholarship_programs for all to authenticated
using (true) with check (true);

create policy "signed in users manage scholars"
on scholars for all to authenticated
using (true) with check (true);

create policy "signed in users manage submissions"
on grade_submissions for all to authenticated
using (true) with check (true);
